name: Global Music API Proxy Worker

on:
  repository_dispatch:
    types: [fetch_album]
  workflow_dispatch:
    inputs:
      artist:
        description: 'Имя артиста'
        required: true
        default: 'The Offspring'
      album:
        description: 'Название альбома'
        required: true
        default: 'Americana'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Music Migration Script
        env:
          ARTIST_PAYLOAD: ${{ github.event.client_payload.artist || inputs.artist }}
          ALBUM_PAYLOAD: ${{ github.event.client_payload.album || inputs.album }}
        run: |
          python app.py

      - name: Commit and Push Updated JSON Database
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          # Проверяем, изменился ли или создался файл базы данных
          if [ -f albums_db.json ]; then
            git add albums_db.json
            if git diff --staged --quiet; then
              print "No changes to commit in albums_db.json"
            else
              git commit -m "database: auto-update albums_db.json [skip ci]"
              git push
            fi
          fi

      - name: Upload Albums JSON Database to Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: updated-music-database
          path: albums_db.json
          retention-days: 7
