name: 'Fetch Album from MusicBrainz'

on:
  repository_dispatch:
    types: [fetch_album]
  workflow_dispatch:
    inputs:
      artist_payload:
        description: 'Artist name'
        required: true
        
      album_payload:
        description: 'Album title'
        required: true

jobs:
  fetch_album_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      - name: Set up Python Environment
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          pip install requests PyYAML

      - name: Fetch Album Data from MusicBrainz API
        env:
          ARTIST_PAYLOAD: ${{ inputs.artist_payload }}
          ALBUM_PAYLOAD: $${{ inputs.album_payload }}
        run: python app.py
        
      - name: Upload Albums JSON Database to Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: updated-music-database
          path: albums_db.json
