name: 'Fetch Album from MusicBrainz'

on:
  # Запуск по заданным аргументам через workflow_dispatch или repository_dispatch
  workflow_dispatch:

# music_worker.yml

jobs:
  fetch_album:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      - name: Set up Python Environment
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          pip install requests PyYAML

      - name: Execute Music Migration Script
        env:
          ARTIST_PAYLOAD: ${{ github.event.inputs.artist || inputs.artist }}
          ALBUM_PAYLOAD: $${{ github.event.inputs.album || inputs.album }}
        run: python app.py  # Используем исправленный app.py
        
      - name: Upload Albums JSON Database to Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: updated-music-database
          path: albums_db.json
